### ISSUE TITLE
Make discord social login go through the discord app instead of website

### ISSUE THREAD

**Issue by TheEveEye** [Project-Skill-Tree/Skill-Tree-API#132]
Simply set the URL to `discord://oauth2/authorize...`
From my experiments, if the discord app isn't available, it automatically open it in the web and gives that little bar on the top for the user to download the discord app

**Comment by OmerSabic** [comment]
Can you link to the documentation that shows this?

**Comment by OmerSabic** [comment]
This is undocumented code that might or might not work. I'll close the issue for now, we could revisit it in the future.
