### ISSUE TITLE
Admin panel for skill tree

### ISSUE THREAD

**Issue by OmerSabic** [Project-Skill-Tree/Skill-Tree-API#21]
Simple panel to add, edit and remove skills from the tree.

- [x] Front-End (with bootstrap)
- [x] Back-End (just CRUD for skills)

**Comment by swatarianess** [comment]
Could be done with swagger, just FYI 😎

**Comment by OmerSabic** [comment]
@swatarianess The panel is supposed to be a GUI for editing the tree. Less errors would be made when editing, that's atleast the goal.

**Comment by swatarianess** [comment]
> @swatarianess Seems like a good idea for the users to view it. We might need to work on a design for it later though lol. I was just gonna make it as simple as possible since it's only accessed by admins.

Yea for sure. Sounds good.
