### ISSUE TITLE
Fix removing complete skills makes XP go negative

### ISSUE THREAD

**Issue by seanjhardy** [Project-Skill-Tree/Skill-Tree-API#36]
XP goes negative when user's undo completed skills, but it should be checking that the task was actually completed and awarded XP. Instead, it takes XP away even for the starting difficulty skills (med 1/2, fit 1/2, journaling 1/2 etc) which were not granted XP

**Comment by swatarianess** [comment]
Just for a visual on what exactly that looks like.

![image](https://user-images.githubusercontent.com/1682734/179398410-7319768d-078b-4a91-84c6-cc25be72e0c5.png)
