### ISSUE TITLE
Deprecate `/v1/users/updateXPHistory` endpoint

### ISSUE THREAD

**Issue by OmerSabic** [Project-Skill-Tree/Skill-Tree-API#76]
It is really unsafe to leave the endpoint open as it writes data directly to the database with no possible way for us to check whether it is true or not. Having it as a separate helper function that is run alongside any time we add XP would be much better and safer.

**Comment by thewildofficial** [comment]
how would the check look like?
i mean, right now users can't directly access the endpoint right
where exactly is the vulnarability?

**Comment by OmerSabic** [comment]
@thewildofficial 
Actually, the user can directly access the endpoint. The way it currently functions is the client makes a request to finish a task and the server hands the user XP and then the ***client*** makes another request to update the XP history. 

A more secure way would be for the server to add the XP history when a task is completed, rather than having the client do it themselves.

Since we were using the bot it wasn't much of an issue as the client was still a server and the users had limited accessibility to it. But this way the user has access to all endpoints and we have to be careful with what we reveal.
