### ISSUE TITLE
Add maybe 1% of the xp of a task each time a task it's checked (and remove it when unchecked

### ISSUE THREAD

**Issue by seanjhardy** [Project-Skill-Tree/Skill-Tree-API#83]

**Comment by OmerSabic** [comment]
Could you explain this more? The user would get a portion of the XP of a task each time they check it off for the day, and then get the rest once it is completed? Would this be put in the chest or directly added to the user?

Need to make sure I'm getting this right.

**Comment by seanjhardy** [comment]
Ignore this weirdness about removing it (idk what I was thinking). Just implement some way to add xp for each time they check off. I was thinking 1% of the skill but maybe a flat rate of like 5xp is better

**Comment by seanjhardy** [comment]
Wait I finally understood what I meant. It means if they uncheck on the same day, they should remove that amount of XP so that they can't game the system and keep checking and unchecking for infinite xp

**Comment by seanjhardy** [comment]
Also this doesn't take a portion of the xp for a skill and take it away at the end, this is just on top of the existing amount
